name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
#     - name: Build the Docker image
#       run: docker build -t chunwarayut/tactive:latest .
      
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chunwarayut/tactive:latest
        
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        private_key: ${{ secrets.SSH_KEY }}
        command: docker pull chunwarayut/tactive:latest && docker stop tactive && docker rm tactive && docker run --name tactive --restart=always -d -p 6050:3000 chunwarayut/tactive 

